project:
  type: website

website:
  title: "ISSS608_demo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: "In-class_Ex/In-Class Exercise 3/In-Class Exercise 3.html"
        text: "In-Class Exercise 3"
      - about.qmd

format:
  html:
    theme: united
    css: styles.css
    toc: true

editor: visual

